name: ÊµãËØï

on: 
  repository_dispatch:
  workflow_dispatch:
    inputs:
      resource_directory:
        type: choice
        description: 'Ë∑ØÁî±Âô®ËµÑÊ∫êÁõÆÂΩï'
        options:
        - "XIAOMI-4A_GIGABit"
        - "XIAOMI-4A_100M"
      repo_url:
        description: '‰ªìÂ∫ìÂú∞ÂùÄ'
        default: 'https://github.com/openwrt/openwrt'
      repo_branch:
        description: 'ÁâàÊú¨ÂàÜÊîØ'
        default: 'v21.02.1'
      feeds_file:
        type: choice
        description: 'ÊõøÊç¢ËΩØ‰ª∂Ê∫êÈÖçÁΩÆ'
        options:
        - "true"
        - "false"
      config_file:
        description: 'config Êñá‰ª∂ÂêçÁß∞'
        default: '.config'
      files_path:
        type: choice
        description: 'ÂØºÂÖ•Ë°•‰∏ÅÁõÆÂΩï'
        options:
        - "true"
        - "false"
      openwrt_patch:
        type: choice
        description: 'ÊâßË°å‰ªìÂ∫ìËÑöÊú¨'
        options:
        - "true"
        - "false"
      befor_patch:
        type: choice
        description: 'ÊâßË°åÁºñËØëÂâçËÑöÊú¨'
        options:
        - "true"
        - "false"
      after_patch:
        type: choice
        description: 'ÊâßË°åÁºñËØëÂêéËÑöÊú¨'
        options:
        - "true"
        - "false"
      upload_release:
        type: choice
        description: 'ÂèëÂ∏ÉÂà∞release'
        options:
        - "false"
        - "true"
env:
  TIMEZONE: Asia/Shanghai
  Resoure_DIR: ${{ github.event.inputs.resource_directory }}
  
  REPO_URL: ${{ github.event.inputs.repo_url }}
  
  REPO_BRANCH: ${{ github.event.inputs.repo_branch }}
  CONFIG_FILE: '${{ github.event.inputs.resource_directory }}/${{ github.event.inputs.config_file }}'
  FEEDS_FILE: '${{ github.event.inputs.resource_directory }}/feeds.conf.default'
  REPLACE_FEEDS: ${{ github.event.inputs.feeds_file }}
  LOAD_FILES: ${{ github.event.inputs.files_path }}
  FILES_PATH: '${{ github.event.inputs.resource_directory }}/files'
  RUN_OPENWRTPATCH: ${{ github.event.inputs.openwrt_patch }}
  OPENWRT_PATCH: '${{ github.event.inputs.resource_directory }}/openwrt_patch.sh'
  RUN_BEFORPATCH: ${{ github.event.inputs.befor_patch }}
  BEFOR_PATCH: '${{ github.event.inputs.resource_directory }}/make_befor.sh'
  RUN_AFTERPATCH: ${{ github.event.inputs.after_patch }}
  AFTER_PATCH: '${{ github.event.inputs.resource_directory }}/make_after.sh'
  UPLOAD_RELEASE: ${{ github.event.inputs.upload_release }}
  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Ê£ÄÂá∫‰ªìÂ∫ìÊï∞ÊçÆ
      uses: actions/checkout@main

    - name: ÂàùÂßãÂåñÁºñËØëÁéØÂ¢É
      env:
        DEBIAN_FRONTEND: noninteractive
        #Èùû‰∫§‰∫íÂºèÁéØÂ¢É
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TIMEZONE"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
    
    - name: ÊèêÂèñÁ°¨‰ª∂‰ø°ÊÅØ
      working-directory: /workdir
      run: |
         echo -e "CPU: $(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
         echo -e "UserName: $(whoami) \n"
         echo -e "SystemInfo: \n$(lsb_release  -a 2>&1 | grep -vi 'No LSB') \n"
         
    - name: ÊãâÂèñOpenWRT‰ªìÂ∫ì
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        
    - name: ÊõøÊç¢ËΩØ‰ª∂Ê∫êÈÖçÁΩÆ
      if: env.REPLACE_FEEDS == 'true'
      run: |
        [ -e $FEEDS_FILE ] && rm -f openwrt/feeds.conf.default
        [ -e $FEEDS_FILE ] && mv $FEEDS_FILE openwrt/feeds.conf.default
    
    - name: Âä†ËΩΩÂõ∫‰ª∂ÈÖçÁΩÆ
      run: mv $CONFIG_FILE openwrt/.config
      
    - name: ÂØºÂÖ•Ë°•‰∏ÅÁõÆÂΩï
      if: env.LOAD_FILES == 'true'
      run: |
        [ -e $FILES_PATH ] && mv $FILES_PATH openwrt/files
        [ -e openwrt/files ] && ls openwrt/files
    
    - name: ÊâßË°å‰ªìÂ∫ìËÑöÊú¨
      if: env.RUN_OPENWRTPATCH == 'true'
      run: |
        chmod +x $OPENWRT_PATCH
        cd openwrt
        $GITHUB_WORKSPACE/$OPENWRT_PATCH
        
    - name: Êõ¥Êñ∞Âπ∂ÂÆâË£ÖËΩØ‰ª∂Ê∫ê
      run: |
        cd openwrt 
        ./scripts/feeds update -a && ./scripts/feeds install -a
        ./scripts/feeds update -a && ./scripts/feeds install -a
    
    - name: ÊâßË°åÁºñËØëÂâçËÑöÊú¨
      if: env.RUN_BEFORPATCH == 'true'
      run: |
        chmod +x $BEFOR_PATCH
        cd openwrt
        $GITHUB_WORKSPACE/$BEFOR_PATCH
    
    - name: ‰∏ãËΩΩÁºñËØëÊâÄÈúÄ
      id: makedownload
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
        
    - name: ÁºñËØëÂõ∫‰ª∂
      id: make
      run: |
        cd openwrt
        echo -e "$(nproc) thread cpu"
        echo "Start Time: "$(date +"%Y/%m/%d %H:%M:%S")""
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "End Time: "$(date +"%Y/%m/%d %H:%M:%S")""
        echo "::set-output name=status::success"
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
    
    - name: ÊâßË°åÁºñËØëÂêéËÑöÊú¨
      if: env.RUN_AFTERPATCH == 'true'
      run: |
        chmod +x $AFTER_PATCH
        cd openwrt
        $GITHUB_WORKSPACE/$AFTER_PATCH
    
    - name: ‰∏ä‰º†Âõ∫‰ª∂
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}
    
    - name: Ê∏ÖÁêÜActionsRunsÊóßÊï∞ÊçÆ
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 5
        
    - name: ÁîüÊàêreleaseÊ†áÁ≠æ
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
        touch release.txt
        [ $UPLOAD_COWTRANSFER = true ] && echo "üîó [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
        [ $UPLOAD_WETRANSFER = true ] && echo "üîó [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
        echo "::set-output name=status::success"
        
    - name: ‰∏ä‰º†Âõ∫‰ª∂Âà∞Release
      uses: softprops/action-gh-release@v1
      if: env.UPLOAD_RELEASE == 'true' && steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
        
    - name: Ê∏ÖÁêÜReleasesÊóßÊï∞ÊçÆ
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 2
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
